pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

includeBuild('../HutosLib') {
    dependencySubstitution {
        substitute module('com.vincenthuto.hutoslib:hutoslib') using project(':')
    }
}

