"""Export accepted Blockbench models and collision geometry. Run from any directory."""
import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / 'src/main/resources/assets/hemomancy'
MODELS = ASSETS / 'models/block'
sources = [json.loads((MODELS / 'bbmodel' / (name + '.bbmodel')).read_text(encoding='utf-8'))
           for name in ['ghastly_alembic', 'ghastly_alembic_condenser', 'ghastly_alembic_athanor']]
for name, model in zip(['condenser', 'athanor'], sources[1:]):
    atlas = 'ghastly_alembic_' + name + '_atlas'
    (ASSETS / 'textures/block' / (atlas + '.png')).write_bytes(base64.b64decode(model['textures'][0]['source'].split(',')[1]))
    exported = dict(parent='minecraft:block/block', render_type='minecraft:cutout',
                    textures={'atlas': 'hemomancy:block/' + atlas, 'particle': 'hemomancy:block/hematic_iron_block'},
                    elements=[])
    for cube in model['elements']:
        assert not any(cube.get('rotation', [0,0,0])), 'Rotated cubes require an exporter update'
        exported['elements'].append(dict(name=cube['name'], **{'from':cube['from'], 'to':cube['to']},
                                       faces={side: dict(uv=face['uv'], texture='#atlas') for side,face in cube['faces'].items()}))
    (MODELS / ('ghastly_alembic_' + name + '.json')).write_text(json.dumps(exported, indent=2)+'\n')

java = '''package com.vincenthuto.hemomancy.common.block.harbinger.crafting;

import java.util.LinkedHashMap;
import java.util.Map;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.phys.shapes.BooleanOp;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;

/** Generated by tools/model_export/export_alembic_upgrades.py from the editable models. */
public final class AlembicGeometry {
    public static final double ATHANOR_LIFT = 7.0 / 16.0;
    private static final double[][][] BOXES = {
'''
for stage, model in enumerate(sources):
    java += '        {\n'
    for cube in model['elements']:
        values = cube['from'] + cube['to']
        if stage == 2:
            values = [v+7 if i in [1,4] else v for i,v in enumerate(values)]
        java += '            {' + ', '.join(str(float(v)) for v in values) + '},\n'
    java += '        },\n'
java += '''    };
    private static final Map<BlockPos, VoxelShape>[][] CELLS = buildCells();

    private AlembicGeometry() {}

    public static Map<BlockPos, VoxelShape> cells(int stage, Direction facing) {
        return CELLS[Math.clamp(stage, 0, 2)][facing.get2DDataValue()];
    }

    public static VoxelShape shape(int stage, Direction facing, BlockPos offset) {
        return cells(stage, facing).getOrDefault(offset, Shapes.empty());
    }

    @SuppressWarnings("unchecked")
    private static Map<BlockPos, VoxelShape>[][] buildCells() {
        Map<BlockPos, VoxelShape>[][] result = new Map[3][4];
        for (int stage = 0; stage < 3; stage++) {
            for (Direction facing : Direction.Plane.HORIZONTAL) {
                Map<BlockPos, VoxelShape> cells = new LinkedHashMap<>();
                for (double[] box : BOXES[stage]) {
                    double x0=box[0], z0=box[2], x1=box[3], z1=box[5];
                    int turns = switch (facing) { case EAST -> 1; case SOUTH -> 2; case WEST -> 3; default -> 0; };
                    for (int turn = 0; turn < turns; turn++) {
                        double nextX0=16-z1, nextX1=16-z0;
                        z0=x0; z1=x1; x0=nextX0; x1=nextX1;
                    }
                    VoxelShape shape = Block.box(x0, box[1], z0, x1, box[4], z1);
                    for (int x=(int)Math.floor(x0/16); x<(int)Math.ceil(x1/16); x++)
                        for (int y=(int)Math.floor(box[1]/16); y<(int)Math.ceil(box[4]/16); y++)
                            for (int z=(int)Math.floor(z0/16); z<(int)Math.ceil(z1/16); z++) {
                                BlockPos offset = new BlockPos(x,y,z);
                                VoxelShape clipped = Shapes.join(shape.move(-x,-y,-z), Shapes.block(), BooleanOp.AND);
                                cells.merge(offset, clipped, Shapes::or);
                            }
                }
                cells.replaceAll((offset, shape) -> shape.optimize());
                result[stage][facing.get2DDataValue()] = Map.copyOf(cells);
            }
        }
        return result;
    }
}
'''
(ROOT / 'src/main/java/com/vincenthuto/hemomancy/common/block/harbinger/crafting/AlembicGeometry.java').write_text(java)
states = json.loads((ASSETS / 'blockstates/ghastly_alembic.json').read_text())
states['multipart'] = [p for p in states['multipart'] if p['apply']['model'] != 'hemomancy:block/ghastly_alembic_upgraded']
for part in states['multipart']:
    part['when']['stage'] = '0'
states['multipart'] += [dict(when={'stage':stage}, apply={'model':'hemomancy:block/ghastly_alembic_upgraded'}) for stage in ['1','2']]
(MODELS / 'ghastly_alembic_upgraded.json').write_text(json.dumps(dict(parent='minecraft:block/block',
    textures={'particle':'hemomancy:block/hematic_iron_block'}, elements=[]),indent=2)+'\n')
(ASSETS / 'blockstates/ghastly_alembic.json').write_text(json.dumps(states,indent=2)+'\n')
print('Exported Condenser/Athanor models, atlases, blockstates, and rotated collision geometry.')
