"""Export the pale, broad-headed ice fish without regenerating other aquatic assets."""
import json
import math
from pathlib import Path
import pelagic_ecology as mesh


def fish():
    mesh.COLORS.update(ice_skin=(206, 221, 216, 255), ice_back=(139, 164, 168, 255),
                       ice_head=(220, 230, 221, 255), ice_eye=(20, 38, 48, 255),
                       ice_iris=(105, 160, 184, 255), ice_mouth=(99, 129, 139, 255))
    r = mesh.Rig('ice_fish', (0, 21.5, 0))
    r.cube('body', (-2, -1.5, -2.5, 4, 3, 6), 'ice_skin')
    r.cube('body', (-1.5, -1.75, -2, 3, .5, 5.5), 'ice_back')
    r.cube('body', (-2.75, -1.5, -6, 5.5, 2.5, 4), 'ice_head')
    r.cube('body', (-2, -.75, -9, 4, 1.25, 3.5), 'ice_head')
    r.cube('body', (-1.5, .25, -9.25, 3, .25, .5), 'ice_mouth')
    for side in (-1, 1):
        r.cube('body', ((-3 if side < 0 else 2.5), -1.75, -5.5, .5, 1.5, 1.5), 'ice_eye')
        r.cube('body', ((-3.25 if side < 0 else 3), -1.25, -5.25, .25, .75, .75), 'ice_iris')
        p = r.part(('left' if side < 0 else 'right') + '_pectoral', 'body', (side * 1.75, .5, -2))
        r.cube(p, ((-3.5 if side < 0 else -.25), -.25, -.25, 3.75, .5, 3), 'fin')
        r.cube(p, ((-4 if side < 0 else 1), -.25, 1.5, 3, .5, 2), 'fin')
        p = r.part(('left' if side < 0 else 'right') + '_pelvic', 'body', (side, 1.25, .5))
        r.cube(p, ((-1.5 if side < 0 else -.25), -.25, -.25, 1.75, .5, 2.5), 'fin')
    r.part('dorsal', 'body', (0, -1.5, -2))
    r.cube('dorsal', (-.25, -2.5, -.25, .5, 3, 2.5), 'fin')
    r.cube('dorsal', (-.25, -1.5, 2, .5, 2, 3.5), 'fin')
    r.part('tail', 'body', (0, 0, 3))
    r.cube('tail', (-1.25, -1, -.5, 2.5, 2, 3.5), 'ice_skin')
    r.cube('tail', (-.25, -2.25, -.25, .5, 1.5, 3), 'fin')
    r.cube('tail', (-.25, .75, -.25, .5, 1.5, 3), 'fin')
    r.part('tail_tip', 'tail', (0, 0, 2.5))
    r.cube('tail_tip', (-.5, -.75, -.5, 1, 1.5, 2.5), 'ice_skin')
    r.cube('tail_tip', (-.25, -2, 1.5, .5, 4, 1.5), 'fin')
    r.cube('tail_tip', (-.25, -2.75, 2.5, .5, 1.5, 1.5), 'fin')
    r.cube('tail_tip', (-.25, 1.25, 2.5, .5, 1.5, 1.5), 'fin')
    return r


def main():
    root = Path(__file__).resolve().parents[2]
    assets = root / 'src/main/resources/assets/hemomancy'
    mesh.ASSETS = root / 'build/ice-fish-assets'
    mesh.SIZE = (128, 128)
    body = mesh.export(fish(), True)
    java = root / 'src/main/java/com/vincenthuto/hemomancy/client/model/entity/mob/aquatic/IceFishMesh.java'
    java.write_text('''package com.vincenthuto.hemomancy.client.model.entity.mob.aquatic;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/** Generated by tools/model_export/ice_fish.py; animation lives in IceFishModel. */
public final class IceFishMesh {
    private IceFishMesh() {}
    public static LayerDefinition create() {
''' + body + '\n    }\n}\n', encoding='utf-8')
    (assets / 'textures/entity/ice_fish.png').write_bytes(
        (mesh.ASSETS / 'textures/entity/pelagic/ice_fish.png').read_bytes())
    model = json.loads((mesh.ASSETS / 'models/entity/bbmodel/pelagic/ice_fish.bbmodel').read_text(encoding='utf-8'))
    groups = {}
    def collect(nodes):
        for node in nodes:
            if isinstance(node, dict):
                groups[node['name']] = node['uuid']
                collect(node['children'])
    collect(model['outliner'])
    animators = {}
    for name, amplitude, phase, axis in [('tail', 16, 0, 'y'), ('tail_tip', 22, -.7, 'y'),
                                          ('left_pectoral', 8, 0, 'z'), ('right_pectoral', -8, 0, 'z')]:
        frames = []
        for time in (0, .25, .5, .75, 1):
            rotation = dict(x=0, y=0, z=0)
            rotation[axis] = math.sin(time * math.tau + phase) * amplitude
            # Blockbench flips the Java rig's Z rotation.
            if axis == 'z': rotation['z'] *= -1
            frames.append(dict(channel='rotation', time=time, interpolation='catmullrom',
                               data_points=[rotation], uuid=mesh.uid(f'ice_fish/swim/{name}/{time}')))
        animators[groups[name]] = dict(name=name, type='bone', keyframes=frames)
    model['animations'] = [dict(uuid=mesh.uid('ice_fish/swim'), name='swim', loop='loop', length=1, animators=animators)]
    (assets / 'models/entity/bbmodel/IceFish.bbmodel').write_text(json.dumps(model, indent=2) + '\n', encoding='utf-8')
    print(f'Exported Ice Fish: {len(model["elements"])} quarter-grid cubes and connected swimming joints.')


if __name__ == '__main__':
    main()
