"""Author the quarter-grid skeletal vulture, atlas and editable flight preview.

Uses the established Rig/UV exporter without regenerating any Pelagic assets.
"""
import json
import math
from pathlib import Path
import pelagic_ecology as mesh


def vulture():
    mesh.COLORS.update(bone=(211, 198, 169, 255), dark=(53, 49, 53, 255),
                       feather=(77, 69, 67, 255), rust=(157, 85, 58, 255),
                       beak=(105, 91, 75, 255), eye=(218, 86, 54, 255))
    r = mesh.Rig('osteophage', (0, 12, 0))
    r.cube('body', (-.75, -4.5, -3, 1.5, 1.5, 12), 'bone')
    r.cube('body', (-2.5, -5.25, -1, 5, 1.5, 10), 'feather')
    r.cube('body', (-.5, -1, -3.5, 1, 5, 9), 'bone')
    # Open rib cage, rather than a solid body painted to resemble a skeleton.
    for i in range(5):
        z = -2.5 + i * 2
        for side in (-1, 1):
            r.cube('body', (side * 2.5 - .5, -3.5, z, 1, 6, .75), 'bone')
        r.cube('body', (-2.5, 2, z, 5, 1, .75), 'bone')
    r.cube('body', (-2, -3, -4.5, 4, 4, 1.5), 'rust')
    r.part('neck', 'body', (0, -3, -3.5))
    r.cube('neck', (-1, -5, -1, 2, 5.5, 2), 'bone')
    for i in range(3):
        r.cube('neck', (-1.25, -1.5 - i * 1.5, -1.25, 2.5, .75, 2.5), 'bone')
    r.part('head', 'neck', (0, -4.5, -.5))
    r.cube('head', (-2.5, -3.5, -3, 5, 4, 4.5), 'bone')
    r.cube('head', (-1.5, -1, -4.5, 3, 1.5, 2.5), 'bone')
    r.cube('head', (-1, -2, -6, 2, 1.5, 3), 'beak')
    r.cube('head', (-.75, -1.25, -6, 1.5, 2, 1), 'beak')
    for side in (-1, 1):
        r.cube('head', (side * 2.25 - .25, -2.75, -2.75, .5, 1.5, 2), 'dark')
        r.cube('head', ((-2.75 if side < 0 else 2.5), -2.25, -2.25, .25, .5, .75), 'eye')
    r.cube('head', (-.75, 0, -3.75, 1.5, 3, 1), 'dark')
    r.cube('head', (-.5, 2.5, -3.5, 1, 1, .75), 'dark')
    # Shoulder -> elbow -> wrist chains overlap throughout the wingbeat.
    for side, label in [(-1, 'left'), (1, 'right')]:
        wing = r.part(label + '_wing', 'body', (side * 2.75, -3.5, -1), (0, 0, side * -8))
        r.cube(wing, (-.5, -.5, -.5, 1, 5, 1.5), 'bone')
        r.cube(wing, (-.75, 1, .5, 1.5, 4, 4), 'feather')
        arm = r.part(label + '_forearm', wing, (0, 4, 0), (0, 0, side * 8))
        r.cube(arm, (-.5, -.5, -.5, 1, 5.5, 1), 'bone')
        r.cube(arm, (-.75, .5, .5, 1.5, 4.5, 4), 'feather')
        tip = r.part(label + '_primaries', arm, (0, 4.5, 0))
        r.cube(tip, (-.5, -.5, -.5, .75, 4, .75), 'bone')
        for i in range(5):
            r.cube(tip, (-.5, -.25 + i * .5, i * 1.25, 1, 7 - i * .5, 1), 'dark')
        leg = r.part(label + '_leg', 'body', (side * 1.5, 2, 3))
        r.cube(leg, (-.5, -.5, -.5, 1, 5.5, 1), 'bone')
        r.cube(leg, (-.75, 4.25, -.75, 1.5, 1.5, 1.5), 'bone')
        r.cube(leg, (-.5, 5, -.5, .75, 4.5, .75), 'bone')
        for toe in range(3):
            r.cube(leg, (-1.25 + toe, 9, -2.5, .5, .75, 3.25), 'beak')
        r.cube(leg, (-.25, 9, .25, .5, .75, 1.5), 'beak')
    r.part('tail', 'body', (0, 0, 7.5), (-18, 0, 0))
    r.cube('tail', (-1.5, -.5, -.5, 3, 1, 5), 'bone')
    for i in range(5):
        length = 9 - abs(i - 2) * 1.5
        r.cube('tail', (-2.5 + i, -.5, 2.5, 1, 1, length), 'feather')
    return r


def main():
    root = Path(__file__).resolve().parents[2]
    assets = root / 'src/main/resources/assets/hemomancy'
    mesh.ASSETS = root / 'build/osteophage-assets'
    mesh.SIZE = (256, 256)
    body = mesh.export(vulture(), True)
    java = root / 'src/main/java/com/vincenthuto/hemomancy/client/model/entity/mob/animal/OsteophageMesh.java'
    java.write_text('''package com.vincenthuto.hemomancy.client.model.entity.mob.animal;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/** Generated by tools/model_export/osteophage.py; animation lives in OsteophageModel. */
public final class OsteophageMesh {
    private OsteophageMesh() {}
    public static LayerDefinition create() {
''' + body + '\n    }\n}\n', encoding='utf-8')
    texture = assets / 'textures/entity/osteophage.png'
    texture.write_bytes((mesh.ASSETS / 'textures/entity/pelagic/osteophage.png').read_bytes())
    model = json.loads((mesh.ASSETS / 'models/entity/bbmodel/pelagic/osteophage.bbmodel').read_text(encoding='utf-8'))
    groups = {}
    def collect(nodes):
        for node in nodes:
            if isinstance(node, dict):
                groups[node['name']] = node['uuid']
                collect(node['children'])
    collect(model['outliner'])
    animators = {}
    poses = {'body': (-32, 0, 0), 'neck': (-12, 0, 0), 'head': (20, 0, 0),
             'left_wing': (0, 0, -70), 'right_wing': (0, 0, 70),
             'left_leg': (-55, 0, 0), 'right_leg': (-55, 0, 0)}
    for name, rotation in poses.items():
        frames = []
        for time in (0, .25, .5, .75, 1):
            x, y, z = rotation
            if name.endswith('_wing'):
                z += math.sin(time * math.tau) * (12 if name.startswith('left') else -12)
            frames.append(dict(channel='rotation', time=time, interpolation='catmullrom',
                               data_points=[dict(x=x, y=y, z=z)], uuid=mesh.uid(f'osteophage/fly/{name}/{time}')))
        animators[groups[name]] = dict(name=name, type='bone', keyframes=frames)
    model['animations'] = [dict(uuid=mesh.uid('osteophage/fly'), name='flight', loop='loop', length=1, animators=animators)]
    path = assets / 'models/entity/bbmodel/Osteophage.bbmodel'
    path.write_text(json.dumps(model, indent=2) + '\n', encoding='utf-8')
    print(f'Exported Osteophage: {len(model["elements"])} quarter-grid cubes, skeletal ribs and articulated wings.')


if __name__ == '__main__':
    main()
