"""Export the compact eight-arm squid rig, editable Blockbench project and UV atlas."""
import json
import math
from pelagic_ecology import Rig, export, COLORS, JAVA, ASSETS, uid


def squid():
    COLORS.update(mantle=(72, 24, 41, 255), arm=(115, 37, 54, 255), web=(139, 44, 62, 255),
                  barb=(204, 167, 148, 255), eye=(232, 142, 54, 255), pupil=(22, 14, 24, 255))
    rig = Rig('vampire_squid', (0, 12, 0))
    for box in [(-3, -5, -3, 6, 5, 6), (-2.5, -7, -2.5, 5, 2, 5), (-1.75, -8, -1.75, 3.5, 1, 3.5)]:
        rig.cube('body', box, 'mantle')
    for side in (-1, 1):
        name = 'fin_left' if side < 0 else 'fin_right'
        rig.part(name, 'body', (side * 3, -4.5, 0), (0, 0, side * 15))
        rig.cube(name, (-2 if side < 0 else 0, -.25, -1.5, 2, .5, 3), 'arm')
        rig.cube('body', (side * 2 - .75, -4.25, -3.25, 1.5, 1.75, .5), 'eye')
        rig.cube('body', (side * 2 - .25, -4, -3.5, .5, 1.25, .25), 'pupil')
    for arm in range(8):
        ring = f'ring{arm}'
        rig.part(ring, 'body', (0, 0, 0), (0, arm * 45, 0))
        parent = ring
        for joint in range(4):
            name = f'arm{arm}_{joint}'
            rig.part(name, parent, (0, 0, 2.75) if joint == 0 else (0, 2.75, 0),
                     (28 if joint == 0 else -10, 0, 0))
            width = (1.5, 1.5, 1, .5)[joint]
            rig.cube(name, (-width / 2, -.25, -.5, width, 3.25, 1), 'arm')
            # Inward-facing cirri are the source of the shared Barbed Splinters.
            rig.cube(name, (-.25, 1.5, -1.25, .5, .5, 1), 'barb')
            if joint < 2:
                web = f'web{arm}_{joint}'
                rig.part(web, name, (0, 0, 0), (0, 22.5, 0))
                for strip in range(3):
                    rig.cube(web, (strip * .75, 0, -.25, .75, 3 - strip * .5, .25), 'web')
            parent = name
    return rig


def main():
    body = export(squid(), True)
    source = '''package com.vincenthuto.hemomancy.client.model.entity.mob.aquatic;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/** Generated by tools/model_export/vampire_squid.py; pose code lives in VampireSquidModel. */
public final class VampireSquidMesh {
    private VampireSquidMesh() {}
    public static LayerDefinition create() {
''' + body + '\n    }\n}\n'
    (JAVA / 'VampireSquidMesh.java').write_text(source, encoding='utf-8')
    path = ASSETS / 'models/entity/bbmodel/pelagic/vampire_squid.bbmodel'
    model = json.loads(path.read_text(encoding='utf-8'))
    groups = {}
    def collect(nodes):
        for node in nodes:
            if isinstance(node, dict):
                groups[node['name']] = node['uuid']
                collect(node['children'])
    collect(model['outliner'])
    model['animations'] = []
    for label, length in [('swim', 3), ('cloak', 1)]:
        animators = {}
        for arm in range(8):
            for joint in range(4):
                name = f'arm{arm}_{joint}'
                frames = []
                times = [0, .25, .5, .75, 1] if label == 'cloak' else [i * .5 for i in range(7)]
                for time in times:
                    angle = (132 if joint == 0 else 23) * time if label == 'cloak' else math.sin(time * math.tau / 3 - joint * .55 + arm * .35) * (10 + joint * 2)
                    frames.append(dict(channel='rotation', time=time, interpolation='catmullrom',
                        data_points=[dict(x=-angle, y=0, z=0)], uuid=uid(f'vampire_squid/{label}/{name}/{time}')))
                animators[groups[name]] = dict(name=name, type='bone', keyframes=frames)
        model['animations'].append(dict(uuid=uid('vampire_squid/' + label), name=label,
            loop='loop' if label == 'swim' else 'hold', length=length, animators=animators))
    path.write_text(json.dumps(model, indent=2) + '\n', encoding='utf-8')
    print('Exported Vampire Squid: eight four-joint arms, webbing, cirri, fins and swim/cloak previews.')


if __name__ == '__main__':
    main()
