package com.vincenthuto.hemomancy.gametest.journey;

public enum HemoJourneyStage {
	MORTAL_DISPLAY("mortal_display"),
	SANGUINE_INITIATION("sanguine_initiation"),
	FIRST_REMNANT_DISCOVERED("first_remnant_discovered"),
	VICAR_HERMIT_ROAD_REPORT("vicar_hermit_road_report"),
	VESSEL_FILLED("vessel_filled"),
	FORMATION_PROJECTED("formation_projected"),
	LIBER_CRAFTED("liber_crafted"),
	HEMATIC_IRON_CRAFTED("hematic_iron_crafted"),
	LIVING_STAFF_CRAFTED("living_staff_crafted"),
	VICAR_REWARD("vicar_reward"),
	VOTARY_RITE("votary_rite"),
	DEGREE_2_REACHED("degree_2_reached"),
	ALCHEMIST_BRIEFING("alchemist_briefing"),
	CENTRIFUGE_PREPARED("centrifuge_prepared"),
	SEPARATION_STARTED("separation_started"),
	ENZYME_RECOVERED("enzyme_recovered"),
	ALCHEMIST_REWARD("alchemist_reward"),
	BODY_ANSWERS_BRIEFING("body_answers_briefing"),
	BODY_ANSWERS_TINCTURE("body_answers_tincture"),
	RED_TAXONOMY("red_taxonomy"),
	LIVING_BESTIARY_RECORD("living_bestiary_record"),
	LIVING_BESTIARY_SURRENDER("living_bestiary_surrender"),
	HYPHAE_DISCOVERED("hyphae_discovered"),
	ARTIFICER_WORN_VOW_BRIEFING("artificer_worn_vow_briefing"),
	ARTIFICER_ARMATURE_PLACED("artificer_armature_placed"),
	ARTIFICER_HEMATIC_UPGRADE("artificer_hematic_upgrade"),
	ARTIFICER_WORN_VOW_REWARD("artificer_worn_vow_reward"),
	ARTIFICER_WORN_VOW_FITTING("artificer_worn_vow_fitting"),
	ENZYME_MASTERY("enzyme_mastery"),
	INITIATE_RITE("initiate_rite"),
	FIRST_CULTURE("first_culture"),
	WOVEN_VESSEL_TURN_IN("woven_vessel_turn_in"),
	FIRST_MEMORY_WOVEN("first_memory_woven"),
	NOETIC_MARK_RECOGNIZED("noetic_mark_recognized"),
	ARTIFICER_THREE_ANSWERS_BRIEFING("artificer_three_answers_briefing"),
	ARTIFICER_FORK_UPGRADE("artificer_fork_upgrade"),
	ARTIFICER_THREE_ANSWERS_INSPECTION("artificer_three_answers_inspection"),
	ARTIFICER_THREE_ANSWERS_COUNSEL("artificer_three_answers_counsel"),
	ARTIFICER_BARBED_RESEARCH("artificer_barbed_research"),
	ARTIFICER_BARBED_RESEARCH_REWARD("artificer_barbed_research_reward"),
	ARTIFICER_FORK_DEMONSTRATION("artificer_fork_demonstration"),
	ARTIFICER_FORK_FITTING("artificer_fork_fitting"),
	ADEPT_RITE("adept_rite"),
	VEIN_MASON_LESSON("vein_mason_lesson"),
	FIRST_SCAR_CARVED("first_scar_carved"),
	FIRST_SCAR_LEARNED("first_scar_learned"),
	FIRST_EFFIGY_PATTERN("first_effigy_pattern"),
	FIRST_EFFIGY_LOADOUT("first_effigy_loadout"),
	VEIN_MASON_REWARD("vein_mason_reward"),
	ILLUMINATUS_RITE("illuminatus_rite"),
	VEIN_MASON_D5_STRAIN("vein_mason_d5_strain"),
	VEIN_MASON_D5_DIAGNOSIS("vein_mason_d5_diagnosis"),
	VEIN_MASON_D5_TREATMENT("vein_mason_d5_treatment"),
	VEIN_MASON_D5_FORTIFICATION("vein_mason_d5_fortification"),
	VEIN_MASON_D5_REWARD("vein_mason_d5_reward"),
	ARTIFICER_ASSUMED_LIMB_BRIEFING("artificer_assumed_limb_briefing"),
	ARTIFICER_FIRST_LIVING_GRAFT("artificer_first_living_graft"),
	ARTIFICER_ASSUMED_LIMB_REWARD("artificer_assumed_limb_reward"),
	ARTIFICER_LIVING_ARSENAL_DEMONSTRATION("artificer_living_arsenal_demonstration"),
	ARTIFICER_FULL_LIVING_ARSENAL("artificer_full_living_arsenal"),
	ARTIFICER_LIVING_ARSENAL_FITTING("artificer_living_arsenal_fitting"),
	ARTIFICER_CRIMSON_VESTMENT_BRIEFING("artificer_crimson_vestment_briefing"),
	VICAR_CONSECRATION_KIT("vicar_consecration_kit"),
	ARTIFICER_FRAME_CONSECRATED("artificer_frame_consecrated"),
	ARTIFICER_CRIMSON_VESTMENT_INSPECTION("artificer_crimson_vestment_inspection"),
	ARTIFICER_CRIMSON_VESTMENT_COUNSEL("artificer_crimson_vestment_counsel"),
	ARTIFICER_BLOOD_LUST_UPGRADE("artificer_blood_lust_upgrade"),
	ARTIFICER_BLOOD_LUST_DEMONSTRATION("artificer_blood_lust_demonstration"),
	ARTIFICER_BLOOD_LUST_FITTING("artificer_blood_lust_fitting"),
	FOUNDING_FANE("founding_fane"),
	SANCTIFIED_RITE("sanctified_rite"),
	VEIN_MASON_D6_REFERRAL("vein_mason_d6_referral"),
	VEIN_MASON_D6_COUNSEL("vein_mason_d6_counsel"),
	VEIN_MASON_D6_FIRST_ROUTE("vein_mason_d6_first_route"),
	VEIN_MASON_D6_SCAR_CARVED("vein_mason_d6_scar_carved"),
	VEIN_MASON_D6_SCAR_LEARNED("vein_mason_d6_scar_learned"),
	VEIN_MASON_D6_LOADOUT("vein_mason_d6_loadout"),
	VEIN_MASON_D6_SECOND_ROUTE("vein_mason_d6_second_route"),
	VEIN_MASON_D6_REWARD("vein_mason_d6_reward"),
	CHAMBER_RETURNED("chamber_returned"),
	COVENANT_THRONE_BOUND("covenant_throne_bound"),
	COVENANT_VIGIL("covenant_vigil"),
	ARCHON_RITE("archon_rite"),
	ARTIFICER_WEIGHT_OF_FRAME_BRIEFING("artificer_weight_of_frame_briefing"),
	ARTIFICER_MONOLITHIC_FRAME("artificer_monolithic_frame"),
	ARTIFICER_D7_UPGRADE("artificer_d7_upgrade"),
	ARTIFICER_WEIGHT_OF_FRAME_INSPECTION("artificer_weight_of_frame_inspection"),
	ARTIFICER_D7_DEMONSTRATION("artificer_d7_demonstration"),
	ARTIFICER_D7_FITTING("artificer_d7_fitting"),
	QLIPHOTH_COMMUNION("qliphoth_communion"),
	APOTHEOS_CHOICE("apotheos_choice"),
	APOTHEOS_RITE("apotheos_rite"),
	COMPLETE("complete");

	private final String id;

	HemoJourneyStage(String id) {
		this.id = id;
	}

	public String id() {
		return id;
	}
}
