package com.vincenthuto.hemomancy.client.model.entity.mob.aquatic;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/** Generated by tools/model_export/ice_fish.py; animation lives in IceFishModel. */
public final class IceFishMesh {
    private IceFishMesh() {}
    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(1, 1).addBox(-2F, -1.5F, -2.5F, 4F, 3F, 6F)
                .texOffs(23, 1).addBox(-1.5F, -1.75F, -2F, 3F, 0.5F, 5.5F)
                .texOffs(42, 1).addBox(-2.75F, -1.5F, -6F, 5.5F, 2.5F, 4F)
                .texOffs(63, 1).addBox(-2F, -0.75F, -9F, 4F, 1.25F, 3.5F)
                .texOffs(80, 1).addBox(-1.5F, 0.25F, -9.25F, 3F, 0.25F, 0.5F)
                .texOffs(89, 1).addBox(-3F, -1.75F, -5.5F, 0.5F, 1.5F, 1.5F)
                .texOffs(95, 1).addBox(-3.25F, -1.25F, -5.25F, 0.25F, 0.75F, 0.75F)
                .texOffs(99, 1).addBox(2.5F, -1.75F, -5.5F, 0.5F, 1.5F, 1.5F)
                .texOffs(105, 1).addBox(3F, -1.25F, -5.25F, 0.25F, 0.75F, 0.75F), PartPose.offsetAndRotation(0.0000000F, 21.5000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition left_pectoral = body.addOrReplaceChild("left_pectoral", CubeListBuilder.create()
                .texOffs(109, 1).addBox(-3.5F, -0.25F, -0.25F, 3.75F, 0.5F, 3F)
                .texOffs(1, 13).addBox(-4F, -0.25F, 1.5F, 3F, 0.5F, 2F), PartPose.offsetAndRotation(-1.7500000F, 0.5000000F, -2.0000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition left_pelvic = body.addOrReplaceChild("left_pelvic", CubeListBuilder.create()
                .texOffs(13, 13).addBox(-1.5F, -0.25F, -0.25F, 1.75F, 0.5F, 2.5F), PartPose.offsetAndRotation(-1.0000000F, 1.2500000F, 0.5000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition right_pectoral = body.addOrReplaceChild("right_pectoral", CubeListBuilder.create()
                .texOffs(24, 13).addBox(-0.25F, -0.25F, -0.25F, 3.75F, 0.5F, 3F)
                .texOffs(40, 13).addBox(1F, -0.25F, 1.5F, 3F, 0.5F, 2F), PartPose.offsetAndRotation(1.7500000F, 0.5000000F, -2.0000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition right_pelvic = body.addOrReplaceChild("right_pelvic", CubeListBuilder.create()
                .texOffs(52, 13).addBox(-0.25F, -0.25F, -0.25F, 1.75F, 0.5F, 2.5F), PartPose.offsetAndRotation(1.0000000F, 1.2500000F, 0.5000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition dorsal = body.addOrReplaceChild("dorsal", CubeListBuilder.create()
                .texOffs(63, 13).addBox(-0.25F, -2.5F, -0.25F, 0.5F, 3F, 2.5F)
                .texOffs(71, 13).addBox(-0.25F, -1.5F, 2F, 0.5F, 2F, 3.5F), PartPose.offsetAndRotation(0.0000000F, -1.5000000F, -2.0000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create()
                .texOffs(81, 13).addBox(-1.25F, -1F, -0.5F, 2.5F, 2F, 3.5F)
                .texOffs(95, 13).addBox(-0.25F, -2.25F, -0.25F, 0.5F, 1.5F, 3F)
                .texOffs(104, 13).addBox(-0.25F, 0.75F, -0.25F, 0.5F, 1.5F, 3F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 3.0000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition tail_tip = tail.addOrReplaceChild("tail_tip", CubeListBuilder.create()
                .texOffs(113, 13).addBox(-0.5F, -0.75F, -0.5F, 1F, 1.5F, 2.5F)
                .texOffs(1, 22).addBox(-0.25F, -2F, 1.5F, 0.5F, 4F, 1.5F)
                .texOffs(7, 22).addBox(-0.25F, -2.75F, 2.5F, 0.5F, 1.5F, 1.5F)
                .texOffs(13, 22).addBox(-0.25F, 1.25F, 2.5F, 0.5F, 1.5F, 1.5F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 2.5000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
