package com.vincenthuto.hemomancy.client.model.entity.mob.aquatic;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/** Generated by tools/model_export/vampire_squid.py; pose code lives in VampireSquidModel. */
public final class VampireSquidMesh {
    private VampireSquidMesh() {}
    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(1, 1).addBox(-3F, -5F, -3F, 6F, 5F, 6F)
                .texOffs(27, 1).addBox(-2.5F, -7F, -2.5F, 5F, 2F, 5F)
                .texOffs(49, 1).addBox(-1.75F, -8F, -1.75F, 3.5F, 1F, 3.5F)
                .texOffs(65, 1).addBox(-2.75F, -4.25F, -3.25F, 1.5F, 1.75F, 0.5F)
                .texOffs(71, 1).addBox(-2.25F, -4F, -3.5F, 0.5F, 1.25F, 0.25F)
                .texOffs(75, 1).addBox(1.25F, -4.25F, -3.25F, 1.5F, 1.75F, 0.5F)
                .texOffs(81, 1).addBox(1.75F, -4F, -3.5F, 0.5F, 1.25F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 12.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition fin_left = body.addOrReplaceChild("fin_left", CubeListBuilder.create()
                .texOffs(85, 1).addBox(-2F, -0.25F, -1.5F, 2F, 0.5F, 3F), PartPose.offsetAndRotation(-3.0000000F, -4.5000000F, 0.0000000F, 0.0000000F, 0.0000000F, -0.2617994F));
        PartDefinition fin_right = body.addOrReplaceChild("fin_right", CubeListBuilder.create()
                .texOffs(97, 1).addBox(0F, -0.25F, -1.5F, 2F, 0.5F, 3F), PartPose.offsetAndRotation(3.0000000F, -4.5000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.2617994F));
        PartDefinition ring0 = body.addOrReplaceChild("ring0", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition arm0_0 = ring0.addOrReplaceChild("arm0_0", CubeListBuilder.create()
                .texOffs(109, 1).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(116, 1).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 2.7500000F, 0.4886922F, 0.0000000F, 0.0000000F));
        PartDefinition web0_0 = arm0_0.addOrReplaceChild("web0_0", CubeListBuilder.create()
                .texOffs(121, 1).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(1, 15).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(5, 15).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm0_1 = arm0_0.addOrReplaceChild("arm0_1", CubeListBuilder.create()
                .texOffs(9, 15).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(16, 15).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition web0_1 = arm0_1.addOrReplaceChild("web0_1", CubeListBuilder.create()
                .texOffs(21, 15).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(25, 15).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(29, 15).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm0_2 = arm0_1.addOrReplaceChild("arm0_2", CubeListBuilder.create()
                .texOffs(33, 15).addBox(-0.5F, -0.25F, -0.5F, 1F, 3.25F, 1F)
                .texOffs(39, 15).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition arm0_3 = arm0_2.addOrReplaceChild("arm0_3", CubeListBuilder.create()
                .texOffs(44, 15).addBox(-0.25F, -0.25F, -0.5F, 0.5F, 3.25F, 1F)
                .texOffs(49, 15).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition ring1 = body.addOrReplaceChild("ring1", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.7853982F, 0.0000000F));
        PartDefinition arm1_0 = ring1.addOrReplaceChild("arm1_0", CubeListBuilder.create()
                .texOffs(54, 15).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(61, 15).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 2.7500000F, 0.4886922F, 0.0000000F, 0.0000000F));
        PartDefinition web1_0 = arm1_0.addOrReplaceChild("web1_0", CubeListBuilder.create()
                .texOffs(66, 15).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(70, 15).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(74, 15).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm1_1 = arm1_0.addOrReplaceChild("arm1_1", CubeListBuilder.create()
                .texOffs(78, 15).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(85, 15).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition web1_1 = arm1_1.addOrReplaceChild("web1_1", CubeListBuilder.create()
                .texOffs(90, 15).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(94, 15).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(98, 15).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm1_2 = arm1_1.addOrReplaceChild("arm1_2", CubeListBuilder.create()
                .texOffs(102, 15).addBox(-0.5F, -0.25F, -0.5F, 1F, 3.25F, 1F)
                .texOffs(108, 15).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition arm1_3 = arm1_2.addOrReplaceChild("arm1_3", CubeListBuilder.create()
                .texOffs(113, 15).addBox(-0.25F, -0.25F, -0.5F, 0.5F, 3.25F, 1F)
                .texOffs(118, 15).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition ring2 = body.addOrReplaceChild("ring2", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 1.5707963F, 0.0000000F));
        PartDefinition arm2_0 = ring2.addOrReplaceChild("arm2_0", CubeListBuilder.create()
                .texOffs(1, 23).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(8, 23).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 2.7500000F, 0.4886922F, 0.0000000F, 0.0000000F));
        PartDefinition web2_0 = arm2_0.addOrReplaceChild("web2_0", CubeListBuilder.create()
                .texOffs(13, 23).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(17, 23).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(21, 23).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm2_1 = arm2_0.addOrReplaceChild("arm2_1", CubeListBuilder.create()
                .texOffs(25, 23).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(32, 23).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition web2_1 = arm2_1.addOrReplaceChild("web2_1", CubeListBuilder.create()
                .texOffs(37, 23).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(41, 23).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(45, 23).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm2_2 = arm2_1.addOrReplaceChild("arm2_2", CubeListBuilder.create()
                .texOffs(49, 23).addBox(-0.5F, -0.25F, -0.5F, 1F, 3.25F, 1F)
                .texOffs(55, 23).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition arm2_3 = arm2_2.addOrReplaceChild("arm2_3", CubeListBuilder.create()
                .texOffs(60, 23).addBox(-0.25F, -0.25F, -0.5F, 0.5F, 3.25F, 1F)
                .texOffs(65, 23).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition ring3 = body.addOrReplaceChild("ring3", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 2.3561945F, 0.0000000F));
        PartDefinition arm3_0 = ring3.addOrReplaceChild("arm3_0", CubeListBuilder.create()
                .texOffs(70, 23).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(77, 23).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 2.7500000F, 0.4886922F, 0.0000000F, 0.0000000F));
        PartDefinition web3_0 = arm3_0.addOrReplaceChild("web3_0", CubeListBuilder.create()
                .texOffs(82, 23).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(86, 23).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(90, 23).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm3_1 = arm3_0.addOrReplaceChild("arm3_1", CubeListBuilder.create()
                .texOffs(94, 23).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(101, 23).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition web3_1 = arm3_1.addOrReplaceChild("web3_1", CubeListBuilder.create()
                .texOffs(106, 23).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(110, 23).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(114, 23).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm3_2 = arm3_1.addOrReplaceChild("arm3_2", CubeListBuilder.create()
                .texOffs(118, 23).addBox(-0.5F, -0.25F, -0.5F, 1F, 3.25F, 1F)
                .texOffs(1, 31).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition arm3_3 = arm3_2.addOrReplaceChild("arm3_3", CubeListBuilder.create()
                .texOffs(6, 31).addBox(-0.25F, -0.25F, -0.5F, 0.5F, 3.25F, 1F)
                .texOffs(11, 31).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition ring4 = body.addOrReplaceChild("ring4", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 3.1415927F, 0.0000000F));
        PartDefinition arm4_0 = ring4.addOrReplaceChild("arm4_0", CubeListBuilder.create()
                .texOffs(16, 31).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(23, 31).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 2.7500000F, 0.4886922F, 0.0000000F, 0.0000000F));
        PartDefinition web4_0 = arm4_0.addOrReplaceChild("web4_0", CubeListBuilder.create()
                .texOffs(28, 31).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(32, 31).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(36, 31).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm4_1 = arm4_0.addOrReplaceChild("arm4_1", CubeListBuilder.create()
                .texOffs(40, 31).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(47, 31).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition web4_1 = arm4_1.addOrReplaceChild("web4_1", CubeListBuilder.create()
                .texOffs(52, 31).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(56, 31).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(60, 31).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm4_2 = arm4_1.addOrReplaceChild("arm4_2", CubeListBuilder.create()
                .texOffs(64, 31).addBox(-0.5F, -0.25F, -0.5F, 1F, 3.25F, 1F)
                .texOffs(70, 31).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition arm4_3 = arm4_2.addOrReplaceChild("arm4_3", CubeListBuilder.create()
                .texOffs(75, 31).addBox(-0.25F, -0.25F, -0.5F, 0.5F, 3.25F, 1F)
                .texOffs(80, 31).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition ring5 = body.addOrReplaceChild("ring5", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 3.9269908F, 0.0000000F));
        PartDefinition arm5_0 = ring5.addOrReplaceChild("arm5_0", CubeListBuilder.create()
                .texOffs(85, 31).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(92, 31).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 2.7500000F, 0.4886922F, 0.0000000F, 0.0000000F));
        PartDefinition web5_0 = arm5_0.addOrReplaceChild("web5_0", CubeListBuilder.create()
                .texOffs(97, 31).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(101, 31).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(105, 31).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm5_1 = arm5_0.addOrReplaceChild("arm5_1", CubeListBuilder.create()
                .texOffs(109, 31).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(116, 31).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition web5_1 = arm5_1.addOrReplaceChild("web5_1", CubeListBuilder.create()
                .texOffs(121, 31).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(1, 39).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(5, 39).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm5_2 = arm5_1.addOrReplaceChild("arm5_2", CubeListBuilder.create()
                .texOffs(9, 39).addBox(-0.5F, -0.25F, -0.5F, 1F, 3.25F, 1F)
                .texOffs(15, 39).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition arm5_3 = arm5_2.addOrReplaceChild("arm5_3", CubeListBuilder.create()
                .texOffs(20, 39).addBox(-0.25F, -0.25F, -0.5F, 0.5F, 3.25F, 1F)
                .texOffs(25, 39).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition ring6 = body.addOrReplaceChild("ring6", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 4.7123890F, 0.0000000F));
        PartDefinition arm6_0 = ring6.addOrReplaceChild("arm6_0", CubeListBuilder.create()
                .texOffs(30, 39).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(37, 39).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 2.7500000F, 0.4886922F, 0.0000000F, 0.0000000F));
        PartDefinition web6_0 = arm6_0.addOrReplaceChild("web6_0", CubeListBuilder.create()
                .texOffs(42, 39).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(46, 39).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(50, 39).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm6_1 = arm6_0.addOrReplaceChild("arm6_1", CubeListBuilder.create()
                .texOffs(54, 39).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(61, 39).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition web6_1 = arm6_1.addOrReplaceChild("web6_1", CubeListBuilder.create()
                .texOffs(66, 39).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(70, 39).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(74, 39).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm6_2 = arm6_1.addOrReplaceChild("arm6_2", CubeListBuilder.create()
                .texOffs(78, 39).addBox(-0.5F, -0.25F, -0.5F, 1F, 3.25F, 1F)
                .texOffs(84, 39).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition arm6_3 = arm6_2.addOrReplaceChild("arm6_3", CubeListBuilder.create()
                .texOffs(89, 39).addBox(-0.25F, -0.25F, -0.5F, 0.5F, 3.25F, 1F)
                .texOffs(94, 39).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition ring7 = body.addOrReplaceChild("ring7", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 5.4977871F, 0.0000000F));
        PartDefinition arm7_0 = ring7.addOrReplaceChild("arm7_0", CubeListBuilder.create()
                .texOffs(99, 39).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(106, 39).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 2.7500000F, 0.4886922F, 0.0000000F, 0.0000000F));
        PartDefinition web7_0 = arm7_0.addOrReplaceChild("web7_0", CubeListBuilder.create()
                .texOffs(111, 39).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(115, 39).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(119, 39).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm7_1 = arm7_0.addOrReplaceChild("arm7_1", CubeListBuilder.create()
                .texOffs(1, 47).addBox(-0.75F, -0.25F, -0.5F, 1.5F, 3.25F, 1F)
                .texOffs(8, 47).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition web7_1 = arm7_1.addOrReplaceChild("web7_1", CubeListBuilder.create()
                .texOffs(13, 47).addBox(0.0F, 0F, -0.25F, 0.75F, 3.0F, 0.25F)
                .texOffs(17, 47).addBox(0.75F, 0F, -0.25F, 0.75F, 2.5F, 0.25F)
                .texOffs(21, 47).addBox(1.5F, 0F, -0.25F, 0.75F, 2.0F, 0.25F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.3926991F, 0.0000000F));
        PartDefinition arm7_2 = arm7_1.addOrReplaceChild("arm7_2", CubeListBuilder.create()
                .texOffs(25, 47).addBox(-0.5F, -0.25F, -0.5F, 1F, 3.25F, 1F)
                .texOffs(31, 47).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        PartDefinition arm7_3 = arm7_2.addOrReplaceChild("arm7_3", CubeListBuilder.create()
                .texOffs(36, 47).addBox(-0.25F, -0.25F, -0.5F, 0.5F, 3.25F, 1F)
                .texOffs(41, 47).addBox(-0.25F, 1.5F, -1.25F, 0.5F, 0.5F, 1F), PartPose.offsetAndRotation(0.0000000F, 2.7500000F, 0.0000000F, -0.1745329F, 0.0000000F, 0.0000000F));
        return LayerDefinition.create(mesh, 128, 256);
    }
}
