package com.vincenthuto.hemomancy.client.model.entity.mob.animal;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/** Generated by tools/model_export/osteophage.py; animation lives in OsteophageModel. */
public final class OsteophageMesh {
    private OsteophageMesh() {}
    public static LayerDefinition create() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(1, 1).addBox(-0.75F, -4.5F, -3F, 1.5F, 1.5F, 12F)
                .texOffs(30, 1).addBox(-2.5F, -5.25F, -1F, 5F, 1.5F, 10F)
                .texOffs(62, 1).addBox(-0.5F, -1F, -3.5F, 1F, 5F, 9F)
                .texOffs(84, 1).addBox(-3.0F, -3.5F, -2.5F, 1F, 6F, 0.75F)
                .texOffs(90, 1).addBox(2.0F, -3.5F, -2.5F, 1F, 6F, 0.75F)
                .texOffs(96, 1).addBox(-2.5F, 2F, -2.5F, 5F, 1F, 0.75F)
                .texOffs(110, 1).addBox(-3.0F, -3.5F, -0.5F, 1F, 6F, 0.75F)
                .texOffs(116, 1).addBox(2.0F, -3.5F, -0.5F, 1F, 6F, 0.75F)
                .texOffs(122, 1).addBox(-2.5F, 2F, -0.5F, 5F, 1F, 0.75F)
                .texOffs(136, 1).addBox(-3.0F, -3.5F, 1.5F, 1F, 6F, 0.75F)
                .texOffs(142, 1).addBox(2.0F, -3.5F, 1.5F, 1F, 6F, 0.75F)
                .texOffs(148, 1).addBox(-2.5F, 2F, 1.5F, 5F, 1F, 0.75F)
                .texOffs(162, 1).addBox(-3.0F, -3.5F, 3.5F, 1F, 6F, 0.75F)
                .texOffs(168, 1).addBox(2.0F, -3.5F, 3.5F, 1F, 6F, 0.75F)
                .texOffs(174, 1).addBox(-2.5F, 2F, 3.5F, 5F, 1F, 0.75F)
                .texOffs(188, 1).addBox(-3.0F, -3.5F, 5.5F, 1F, 6F, 0.75F)
                .texOffs(194, 1).addBox(2.0F, -3.5F, 5.5F, 1F, 6F, 0.75F)
                .texOffs(200, 1).addBox(-2.5F, 2F, 5.5F, 5F, 1F, 0.75F)
                .texOffs(214, 1).addBox(-2F, -3F, -4.5F, 4F, 4F, 1.5F), PartPose.offsetAndRotation(0.0000000F, 12.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition neck = body.addOrReplaceChild("neck", CubeListBuilder.create()
                .texOffs(227, 1).addBox(-1F, -5F, -1F, 2F, 5.5F, 2F)
                .texOffs(237, 1).addBox(-1.25F, -1.5F, -1.25F, 2.5F, 0.75F, 2.5F)
                .texOffs(1, 18).addBox(-1.25F, -3.0F, -1.25F, 2.5F, 0.75F, 2.5F)
                .texOffs(13, 18).addBox(-1.25F, -4.5F, -1.25F, 2.5F, 0.75F, 2.5F), PartPose.offsetAndRotation(0.0000000F, -3.0000000F, -3.5000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition head = neck.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(25, 18).addBox(-2.5F, -3.5F, -3F, 5F, 4F, 4.5F)
                .texOffs(46, 18).addBox(-1.5F, -1F, -4.5F, 3F, 1.5F, 2.5F)
                .texOffs(59, 18).addBox(-1F, -2F, -6F, 2F, 1.5F, 3F)
                .texOffs(71, 18).addBox(-0.75F, -1.25F, -6F, 1.5F, 2F, 1F)
                .texOffs(78, 18).addBox(-2.5F, -2.75F, -2.75F, 0.5F, 1.5F, 2F)
                .texOffs(85, 18).addBox(-2.75F, -2.25F, -2.25F, 0.25F, 0.5F, 0.75F)
                .texOffs(89, 18).addBox(2.0F, -2.75F, -2.75F, 0.5F, 1.5F, 2F)
                .texOffs(96, 18).addBox(2.5F, -2.25F, -2.25F, 0.25F, 0.5F, 0.75F)
                .texOffs(100, 18).addBox(-0.75F, 0F, -3.75F, 1.5F, 3F, 1F)
                .texOffs(107, 18).addBox(-0.5F, 2.5F, -3.5F, 1F, 1F, 0.75F), PartPose.offsetAndRotation(0.0000000F, -4.5000000F, -0.5000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition left_wing = body.addOrReplaceChild("left_wing", CubeListBuilder.create()
                .texOffs(113, 18).addBox(-0.5F, -0.5F, -0.5F, 1F, 5F, 1.5F)
                .texOffs(120, 18).addBox(-0.75F, 1F, 0.5F, 1.5F, 4F, 4F), PartPose.offsetAndRotation(-2.7500000F, -3.5000000F, -1.0000000F, 0.0000000F, 0.0000000F, 0.1396263F));
        PartDefinition left_forearm = left_wing.addOrReplaceChild("left_forearm", CubeListBuilder.create()
                .texOffs(133, 18).addBox(-0.5F, -0.5F, -0.5F, 1F, 5.5F, 1F)
                .texOffs(139, 18).addBox(-0.75F, 0.5F, 0.5F, 1.5F, 4.5F, 4F), PartPose.offsetAndRotation(0.0000000F, 4.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, -0.1396263F));
        PartDefinition left_primaries = left_forearm.addOrReplaceChild("left_primaries", CubeListBuilder.create()
                .texOffs(152, 18).addBox(-0.5F, -0.5F, -0.5F, 0.75F, 4F, 0.75F)
                .texOffs(157, 18).addBox(-0.5F, -0.25F, 0.0F, 1F, 7.0F, 1F)
                .texOffs(163, 18).addBox(-0.5F, 0.25F, 1.25F, 1F, 6.5F, 1F)
                .texOffs(169, 18).addBox(-0.5F, 0.75F, 2.5F, 1F, 6.0F, 1F)
                .texOffs(175, 18).addBox(-0.5F, 1.25F, 3.75F, 1F, 5.5F, 1F)
                .texOffs(181, 18).addBox(-0.5F, 1.75F, 5.0F, 1F, 5.0F, 1F), PartPose.offsetAndRotation(0.0000000F, 4.5000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition left_leg = body.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(187, 18).addBox(-0.5F, -0.5F, -0.5F, 1F, 5.5F, 1F)
                .texOffs(193, 18).addBox(-0.75F, 4.25F, -0.75F, 1.5F, 1.5F, 1.5F)
                .texOffs(201, 18).addBox(-0.5F, 5F, -0.5F, 0.75F, 4.5F, 0.75F)
                .texOffs(206, 18).addBox(-1.25F, 9F, -2.5F, 0.5F, 0.75F, 3.25F)
                .texOffs(216, 18).addBox(-0.25F, 9F, -2.5F, 0.5F, 0.75F, 3.25F)
                .texOffs(226, 18).addBox(0.75F, 9F, -2.5F, 0.5F, 0.75F, 3.25F)
                .texOffs(236, 18).addBox(-0.25F, 9F, 0.25F, 0.5F, 0.75F, 1.5F), PartPose.offsetAndRotation(-1.5000000F, 2.0000000F, 3.0000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition right_wing = body.addOrReplaceChild("right_wing", CubeListBuilder.create()
                .texOffs(242, 18).addBox(-0.5F, -0.5F, -0.5F, 1F, 5F, 1.5F)
                .texOffs(1, 30).addBox(-0.75F, 1F, 0.5F, 1.5F, 4F, 4F), PartPose.offsetAndRotation(2.7500000F, -3.5000000F, -1.0000000F, 0.0000000F, 0.0000000F, -0.1396263F));
        PartDefinition right_forearm = right_wing.addOrReplaceChild("right_forearm", CubeListBuilder.create()
                .texOffs(14, 30).addBox(-0.5F, -0.5F, -0.5F, 1F, 5.5F, 1F)
                .texOffs(20, 30).addBox(-0.75F, 0.5F, 0.5F, 1.5F, 4.5F, 4F), PartPose.offsetAndRotation(0.0000000F, 4.0000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.1396263F));
        PartDefinition right_primaries = right_forearm.addOrReplaceChild("right_primaries", CubeListBuilder.create()
                .texOffs(33, 30).addBox(-0.5F, -0.5F, -0.5F, 0.75F, 4F, 0.75F)
                .texOffs(38, 30).addBox(-0.5F, -0.25F, 0.0F, 1F, 7.0F, 1F)
                .texOffs(44, 30).addBox(-0.5F, 0.25F, 1.25F, 1F, 6.5F, 1F)
                .texOffs(50, 30).addBox(-0.5F, 0.75F, 2.5F, 1F, 6.0F, 1F)
                .texOffs(56, 30).addBox(-0.5F, 1.25F, 3.75F, 1F, 5.5F, 1F)
                .texOffs(62, 30).addBox(-0.5F, 1.75F, 5.0F, 1F, 5.0F, 1F), PartPose.offsetAndRotation(0.0000000F, 4.5000000F, 0.0000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition right_leg = body.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(68, 30).addBox(-0.5F, -0.5F, -0.5F, 1F, 5.5F, 1F)
                .texOffs(74, 30).addBox(-0.75F, 4.25F, -0.75F, 1.5F, 1.5F, 1.5F)
                .texOffs(82, 30).addBox(-0.5F, 5F, -0.5F, 0.75F, 4.5F, 0.75F)
                .texOffs(87, 30).addBox(-1.25F, 9F, -2.5F, 0.5F, 0.75F, 3.25F)
                .texOffs(97, 30).addBox(-0.25F, 9F, -2.5F, 0.5F, 0.75F, 3.25F)
                .texOffs(107, 30).addBox(0.75F, 9F, -2.5F, 0.5F, 0.75F, 3.25F)
                .texOffs(117, 30).addBox(-0.25F, 9F, 0.25F, 0.5F, 0.75F, 1.5F), PartPose.offsetAndRotation(1.5000000F, 2.0000000F, 3.0000000F, 0.0000000F, 0.0000000F, 0.0000000F));
        PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create()
                .texOffs(123, 30).addBox(-1.5F, -0.5F, -0.5F, 3F, 1F, 5F)
                .texOffs(141, 30).addBox(-2.5F, -0.5F, 2.5F, 1F, 1F, 6.0F)
                .texOffs(157, 30).addBox(-1.5F, -0.5F, 2.5F, 1F, 1F, 7.5F)
                .texOffs(176, 30).addBox(-0.5F, -0.5F, 2.5F, 1F, 1F, 9.0F)
                .texOffs(198, 30).addBox(0.5F, -0.5F, 2.5F, 1F, 1F, 7.5F)
                .texOffs(217, 30).addBox(1.5F, -0.5F, 2.5F, 1F, 1F, 6.0F), PartPose.offsetAndRotation(0.0000000F, 0.0000000F, 7.5000000F, -0.3141593F, 0.0000000F, 0.0000000F));
        return LayerDefinition.create(mesh, 256, 256);
    }
}
