import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

test('materials editor page is wired into Vite API routing and dev output', () => {
  const htmlPath = resolve(process.cwd(), 'materials.html');
  const html = readFileSync(htmlPath, 'utf8');
  const vite = readFileSync(resolve(process.cwd(), 'vite.config.ts'), 'utf8');
  const dev = readFileSync(resolve(process.cwd(), 'scripts/dev.mjs'), 'utf8');
  const server = readFileSync(resolve(process.cwd(), 'src/server/httpServer.ts'), 'utf8');

  expect(existsSync(htmlPath)).toBe(true);
  expect(html).toContain('/src/frontend/materials.ts');
  expect(vite).toContain('materials.html');
  expect(dev).toContain('/materials.html');
  expect(server).toContain("'/api/materials'");
  expect(server).toContain("'/api/materials/preview'");
});

test('materials frontend exposes graph layers inspector creation and editor navigation', () => {
  const source = readFileSync(resolve(process.cwd(), 'src/frontend/materials.ts'), 'utf8');

  expect(source).toContain('material-node');
  expect(source).toContain('atlas-hub');
  expect(source).toContain('renderAtlasHub(layout.hub)');
  expect(source).toContain('data-select-kind="atlas-hub"');
  expect(source).toContain("selection.kind === 'atlas-hub'");
  expect(source).toContain('[data-path-edit]');
  expect(source).toContain('data-action="align-nodes"');
  expect(source).toContain('data-action="align-tolerance-x"');
  expect(source).toContain('data-action="align-tolerance-y"');
  expect(source).toContain('clampAlignmentTolerance');
  expect(source).toContain('{ x: alignToleranceX, y: alignToleranceY }');
  expect(source).toContain('.material-node, .label-plaque, .atlas-hub');
  expect(source).toContain('class="node-frame" x="-13" y="-13" width="26" height="26"');
  expect(source).toContain('class="node-glow" x="-15" y="-15" width="30" height="30"');
  expect(source).toContain('width="16" height="16" preserveAspectRatio');
  expect(source).toContain('viewBox="0 0 ${layout.width} ${layout.height}"');
  expect(source).toContain('rect x="0" y="0" width="${layout.width}" height="${layout.height}"');
  expect(source).not.toContain('atlas-hub-underline');
  expect(source).toContain('category-anchor');
  expect(source).not.toContain('renderCategoryAnchor');
  expect(source).not.toContain('category-anchors');
  expect(source).not.toContain('.material-node, .category-anchor, .label-plaque');
  expect(source).not.toContain('bucket-root');
  expect(source).toContain('label-plaque');
  expect(source).toContain('atlas-trace');
  expect(source).toContain('beginDragPan');
  expect(source).toContain('updateDragPan');
  expect(source).toContain("classList.add('panning')");
  expect(source).toContain('scroller.setPointerCapture(event.pointerId)');
  expect(source).not.toContain('draggable.setPointerCapture(event.pointerId)');
  expect(source).toContain('draggedGraphElementSelector(dragState.kind, dragState.id)');
  expect(source).not.toContain('querySelector<SVGGElement>(`[data-select-kind="${dragState.kind}"][data-select-id="${cssEscape(dragState.id)}"]`)');
  expect(source).toContain('updateMaterialGraphDomTraces()');
  expect(source).toContain('captureGraphViewport');
  expect(source).toContain('restoreGraphViewport');
  expect(source).toContain('renderPreservingGraphViewport(captureCurrentGraphViewport())');
  expect(source).toContain('parentOptionsFor(entry)');
  expect(source).not.toContain('bucketRootParentFor(entry)');
  expect(source).not.toContain('Bucket root parent');
  expect(source).toContain("kind: 'bucket-change'");
  expect(source).toContain('beforeBucketId');
  expect(source).toContain('afterBucketId');
  expect(source).toContain('setEntryBucket(change.id, change.beforeBucketId)');
  expect(source).toContain('setEntryBucket(change.id, change.afterBucketId)');
  expect(source).toContain("kind: 'auto-position-change'");
  expect(source).toContain('beforeNodeX');
  expect(source).toContain('beforeNodeY');
  expect(source).toContain('setEntryNodePosition(change.id, change.beforeNodeX, change.beforeNodeY)');
  expect(source).toContain('setEntryNodePosition(change.id, change.afterNodeX, change.afterNodeY)');
  expect(source).toContain("kind: 'parent-change'");
  expect(source).toContain('parent-pill');
  expect(source).toContain('removeParent(parentId)');
  expect(source).toContain('statusText = `Added ${parentId} as a parent of ${entry.id}.`;');
  expect(source).toContain('if (shouldRender) renderPreservingGraphViewport(captureCurrentGraphViewport());');
  expect(source).toContain('statusText = `Removed ${parentId} from ${entry.id}.`;');
  expect(source).toContain('beginConnectionDrag');
  expect(source).toContain('finishConnectionDrag');
  expect(source).toContain('addParentToEntry(target, rewire.parentField');
  expect(source).not.toContain('selection = { kind: \'material\', id: target.id };\n          addParent(rewire.parentField);');
  expect(source).not.toContain('data-entry-edit="parentIds"');
  expect(source).toContain('create-entry');
  expect(source).toContain('Unknown material');
  expect(source).toContain('Skills');
  expect(source).toContain('Manipulations');
});
